language: bash
dist: trusty
services:
  - docker

stages:
  - name: heroku
    if: branch == master
  - name: docker

jobs:
  include:
    - stage: docker
      name: "Deploy Docker Hub"
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - VER=$TRAVIS_BRANCH-build$TRAVIS_BUILD_NUMBER-`git rev-parse --short HEAD`
        - docker build -t maslick/barkoder-ui:$VER -f docker/Dockerfile .
        - docker tag maslick/barkoder-ui:$VER maslick/barkoder-ui
        - docker push maslick/barkoder-ui:$VER
        - docker push maslick/barkoder-ui
    - stage: heroku
      name: "Deploy to Heroku"
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: ERy46feDk3SILyRDl4TYW26/kb4DFEaHG7ZI82XLuDjg0H1sXo+jcABuLKQ+bzwHyvFUW78Q0XTlfY9wTu9MiMBimT8cpIfb83+7QZr1kR3yXR6lLs4mD0QFbHf9QiiPv4udeQioFoHCxe47LQEciEf0GfSybGG5Y8we+Vxj2yM6Ca+5PWmdttwLdqzn7Q3W0III8abpGYtr/1/fYRuqzeM8nYJBCM5KBZtH8KaTVaGpv25ZUQx/8CXN/VkEa9ehTL9hGEmadzb0yIKMRti8BQBSHHeLevhxEYxmpfbrNut51CKvyDKu3EJl4nNLxs3q9+kIC1Tb6FpvWVOaP9n8XfV/dazuIqLt1ngowtXwMZ3woNYJqZOspD4trXLjBSF2WZdYX37vIGVAunK0hISh6kURJEteJuhWhJQpgFsaiHdWkx51dQJCbYSdaGlJtqO2tWNvXa+DftJFst76oGctvtpiI8Tkdb0xo0NUHJEJe593PbxE0s9XufNsJFSvkF6GhE3RaaSjsk671jYzOhVc9XIAsUjy82MwZHf7QHZPt3b3MfnvNi+R4Lu0ZyLGbzjIfi3os7r3h1X45A9u6a3XPnntqW7DSxsuHfs1T/z/snrOYRa1DrYI8Ld4U1jrzbeVb3cMEqEY9jx2fChQOLSGjEnS2sew0S4eq0IyRIhzNa4=
        app:
          master: barkoder-ui
        on:
          repo: maslick/barkoder-ui
        run:
          - restart
