language: bash
dist: trusty
services:
  - docker
install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t maslick/barkoder-ui:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER -f docker/Dockerfile .
  - docker tag maslick/barkoder-ui:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER maslick/barkoder-ui
  - docker push maslick/barkoder-ui:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - docker push maslick/barkoder-ui
